import streamlit as st
import pandas as pd
import numpy as np
from scipy.optimize import newton
import plotly.express as px

# --- PAGE CONFIGURATION ---
st.set_page_config(page_title="Quantitative Portfolio Engine", page_icon="📈", layout="wide")

st.title("Quantitative Portfolio Management System")
st.markdown("Automated Systematic Investment Tracking & Risk Analytics")
st.divider()

# --- FINANCIAL MATHEMATICS ENGINE ---
def calculate_xirr(cashflows):
    cashflows.sort(key=lambda x: x[0])
    d0 = cashflows[0][0]
    
    def xnpv(r):
        if r <= -1.0: return float('inf')
        return sum([cf / (1 + r)**((d - d0).days / 365.25) for d, cf in cashflows])
        
    try:
        return newton(xnpv, 0.1) 
    except RuntimeError:
        return None

def simulate_sip(df, sip_amount_per_fund=100):
    df_temp = df.copy()
    df_temp['YearMonth'] = df_temp.index.to_period('M')
    sip_dates = df_temp.groupby('YearMonth').head(1).index
    
    cumulative_units = {col: 0.0 for col in df.columns}
    cumulative_invested = {col: 0.0 for col in df.columns}
    
    daily_units = pd.DataFrame(index=df.index, columns=df.columns, dtype=float)
    daily_invested = pd.DataFrame(index=df.index, columns=df.columns, dtype=float)
    
    for date in df.index:
        if date in sip_dates:
            for fund in df.columns:
                nav_today = df.loc[date, fund]
                units_bought = sip_amount_per_fund / nav_today
                
                cumulative_units[fund] += units_bought
                cumulative_invested[fund] += sip_amount_per_fund
                
        daily_units.loc[date] = cumulative_units
        daily_invested.loc[date] = cumulative_invested

    portfolio_value_df = daily_units * df
    portfolio_value_df['Total_Portfolio_Value'] = portfolio_value_df.sum(axis=1)
    daily_invested['Total_Amount_Invested'] = daily_invested.sum(axis=1)
    
    return portfolio_value_df, daily_invested, sip_dates

# --- DATA INGESTION (CACHED) ---
@st.cache_data
def load_data():
    # Reads the CSV generated by your data ingestion script
    df = pd.read_csv("mutual_fund_nav_history.csv", parse_dates=["date"])
    df.set_index("date", inplace=True)
    return df

# --- DASHBOARD RENDERING ---
try:
    df = load_data()
    
    # Run the Simulation
    value_df, invested_df, sip_dates = simulate_sip(df)
    
    # Compile Cashflows for XIRR
    total_monthly_sip = 500.0
    cashflows = [(date, -total_monthly_sip) for date in sip_dates]
    final_value = value_df['Total_Portfolio_Value'].iloc[-1]
    cashflows.append((value_df.index[-1], final_value))
    
    # Calculate Risk Metrics
    xirr_val = calculate_xirr(cashflows)
    daily_returns = value_df['Total_Portfolio_Value'].pct_change().dropna()
    annual_volatility = daily_returns.std() * np.sqrt(252)
    risk_free_rate = 0.07
    annualized_return = daily_returns.mean() * 252
    sharpe_ratio = (annualized_return - risk_free_rate) / annual_volatility
    
    rolling_max = value_df['Total_Portfolio_Value'].cummax()
    drawdown = (value_df['Total_Portfolio_Value'] - rolling_max) / rolling_max
    max_dd = drawdown.min()

    # --- TOP ROW: CORE METRICS ---
    st.subheader("Performance Summary")
    total_invested = invested_df['Total_Amount_Invested'].iloc[-1]
    abs_return = ((final_value - total_invested) / total_invested) * 100
    
    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Current Portfolio Value", f"₹{final_value:,.2f}", f"{abs_return:.2f}% Absolute")
    col2.metric("Total Capital Invested", f"₹{total_invested:,.2f}")
    col3.metric("XIRR (Annualized)", f"{xirr_val * 100:.2f}%" if xirr_val else "N/A")
    col4.metric("Sharpe Ratio", f"{sharpe_ratio:.2f}")

    # --- MIDDLE ROW: RISK METRICS ---
    st.markdown("<br>", unsafe_allow_html=True)
    st.subheader("Institutional Risk Metrics")
    rcol1, rcol2, rcol3 = st.columns(3)
    rcol1.metric("Annualized Volatility", f"{annual_volatility * 100:.2f}%")
    rcol2.metric("Maximum Drawdown", f"{max_dd * 100:.2f}%")
    rcol3.metric("Assumed Risk-Free Rate", "7.00%")

    # --- BOTTOM ROW: INTERACTIVE CHART ---
    st.markdown("<br>", unsafe_allow_html=True)
    st.subheader("Growth Trajectory")
    
    chart_data = pd.DataFrame({
        "Portfolio Value": value_df['Total_Portfolio_Value'],
        "Capital Invested": invested_df['Total_Amount_Invested']
    })
    
    fig = px.line(chart_data, 
                  labels={"value": "Amount (₹)", "date": "Date"}, 
                  title="Asset Appreciation vs. Capital Deployed",
                  color_discrete_sequence=["#1f77b4", "#ff7f0e"])
    
    fig.update_layout(hovermode="x unified")
    st.plotly_chart(fig, width='stretch')
    # --- BOTTOM ROW: ASSET ALLOCATION ---
    st.markdown("<br>", unsafe_allow_html=True)
    st.subheader("Current Asset Allocation")
    
    # Extract the final day's value for each individual fund
    latest_values = value_df.iloc[-1].drop('Total_Portfolio_Value')
    
    # Create a DataFrame for Plotly
    pie_data = pd.DataFrame({
        "Asset": latest_values.index,
        "Current Value": latest_values.values
    })
    
    # Generate an interactive Donut Chart
    fig_pie = px.pie(pie_data, 
                     values="Current Value", 
                     names="Asset", 
                     hole=0.4,
                     title="Portfolio Weight Drift Over Time",
                     color_discrete_sequence=px.colors.sequential.Teal)
    
    fig_pie.update_traces(textposition='inside', textinfo='percent+label')
    st.plotly_chart(fig_pie, width='stretch')

except FileNotFoundError:
    st.error("Data file 'mutual_fund_nav_history.csv' not found. Please ensure it is in the same folder as app.py.")

except FileNotFoundError:
    st.error("Data file 'mutual_fund_nav_history.csv' not found. Please ensure it is in the same folder as app.py.")